language: java
jdk:
  - openjdk11
branches:
  only:
    - master

# Travis CI 서버의 Home
cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.gradle'
script: "./gradlew clean build"

# 실행권한 추가. 없으면 에러남
#before_install:
#  - chmod +x gradlew

# Deploy 전에 설정해줌
before_deploy:
  - mkdir -p before-deploy #zip에 포함시킬 파일들을 담을 디렉토리 생성
  - cp scripts/*.sh before-deploy/
  - cp appspec.yml before-deploy/
  - cp build/libs/*.jar before-deploy/ # build 에러가 계속 나는데 왜그러지?
  - cd before-deploy && zip -r before-deploy * # before-deploy로 이동 후 전체 압축
  - cd ../ && mkdir -p deploy # 상위 디렉토리로 이동 후 deploy 디렉토리 생성
  - mv before-deploy/before-deploy.zip deploy/ODSupport.zip #deploy로 zip 파일 이동
  #- zip -r ODSupport *
  #- mkdir -p deploy
  #- mv ODSupport.zip deploy/ODSupport.zip

deploy:
  - provider: s3
    access_key_id: $AWS_ACCESS_KEY # AWS 접근 키 ( Travis에 지정 )
    secret_access_key: $AWS_SECRET_KEY # AWS 시크릿 키 ( Travis에 지정 )
    bucket: odsupport-build
    region: ap-northeast-2
    skip_cleanup: true
    acl: private # zip 파일 접근
    local_dir: deploy # before_deploy에서 생성한 디렉토리
    wait-until-deployed: true

  - provider: codedeploy
    access_key_id: $AWS_ACCESS_KEY
    secret_access_key: $AWS_SECRET_KEY
    bucket: odsupport-build
    region: ap-northeast-2
    key: ODSupport.zip
    bundle_type: zip
    application: ODSupport # 코드디플로이 어플리케이션 이름
    deployment_group: ODSupport-group # 코드디플로이 배포 그룹 이름
    wait-until-deployed: true #오타정정


# CI 실행 완료 시 메일로 알람
notifications:
  email:
    recipients:
      - cronian89@gmail.com